function createLanguageTypesForSysBioDictionary

global rootFolder
rootFolder = fileparts(which('initSystemsBioinformaticsToolbox'));

SysBio_language_keys = {'language_keys';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'metacyc';'kegg';'kegg';'kegg';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'seed';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'metacyc';'metacyc';'metacyc';'metacyc';'metacyc';'kegg';'kegg';'kegg';'kegg';'kegg';'kegg';'metacyc';'metacyc'};
SysBio_language_values = {'language_values';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg';'bigg'};

save(fullfile(rootFolder, 'MNX','SysBio_language_keys.mat'),'SysBio_language_keys');
save(fullfile(rootFolder, 'MNX','SysBio_language_values.mat'),'SysBio_language_values');

end