function determineNewRelationshipsForBothSpecies

global rootFolder
rootFolder = fileparts(which('initSystemsBioinformaticsToolbox'));
baseFolder = fullfile(rootFolder,'results');


load(fullfile(baseFolder, 'lpl', 'models_lpl.mat'))
load(fullfile(baseFolder, 'bpe', 'models_bpe.mat'))
[relationships1, relationships_equations1, relationships_language1, inMetaNetX1, relationships_MNXIDs1,relationships_modelIndices1] = ...
    readRelationships(fullfile(baseFolder, 'lpl', 'relationships0_lpl'));
[relationships2, relationships_equations2, relationships_language2, inMetaNetX2, relationships_MNXIDs2,relationships_modelIndices2] = ...
    readRelationships(fullfile(baseFolder, 'bpe', 'relationships0_bpe'));

[relationshipsA, relationships_equationsA, relationships_languageA, inMetaNetXA, relationships_MNXIDsA,relationships_modelIndicesA] = ...
    mergeRelationships(...
    relationships1, relationships_equations1, relationships_language1, inMetaNetX1, relationships_MNXIDs1,relationships_modelIndices1,...
    relationships2, relationships_equations2, relationships_language2, inMetaNetX2, relationships_MNXIDs2,relationships_modelIndices2);

[relationships3, relationships_equations3, relationships_language3, inMetaNetX3, relationships_MNXIDs3,relationships_modelIndices3] = ...
    readRelationships(fullfile(baseFolder, 'lpl', 'relationships1_lpl'));
[relationships4, relationships_equations4, relationships_language4, inMetaNetX4, relationships_MNXIDs4,relationships_modelIndices4] = ...
    readRelationships(fullfile(baseFolder, 'bpe', 'relationships1_bpe'));


[relationshipsB, relationships_equationsB, relationships_languageB, inMetaNetXB, relationships_MNXIDsB,relationships_modelIndicesB] = ...
    mergeRelationships(...
    relationships3, relationships_equations3, relationships_language3, inMetaNetX3, relationships_MNXIDs3,relationships_modelIndices3,...
    relationships4, relationships_equations4, relationships_language4, inMetaNetX4, relationships_MNXIDs4,relationships_modelIndices4);

[relationships5, relationships_equations5, relationships_language5, inMetaNetX5, relationships_MNXIDs5,relationships_modelIndices5] = ...
    readRelationships(fullfile(baseFolder, 'lpl', 'relationships2_lpl'));
[relationships6, relationships_equations6, relationships_language6, inMetaNetX6, relationships_MNXIDs6,relationships_modelIndices6] = ...
    readRelationships(fullfile(baseFolder, 'bpe', 'relationships2_bpe'));


[relationshipsC, relationships_equationsC, relationships_languageC, inMetaNetXC, relationships_MNXIDsC,relationships_modelIndicesC] = ...
    mergeRelationships(...
    relationships5, relationships_equations5, relationships_language5, inMetaNetX5, relationships_MNXIDs5,relationships_modelIndices5,...
    relationships6, relationships_equations6, relationships_language6, inMetaNetX6, relationships_MNXIDs6,relationships_modelIndices6);

[notIn1, ind2, notIn2, ind1] = findNewRelationships(relationshipsA, relationshipsB);
n_notInMetaNetXB = length(find(inMetaNetXB==0));
exportNewRelationships_general(relationshipsB, relationships_equationsB, ...
    relationships_languageB, inMetaNetXB, n_notInMetaNetXB, relationships_MNXIDsB, ...
   relationships_modelIndicesB, ind2, 'newRel_global1', 'lpl_bpe')

[notIn1, ind2, notIn2, ind1] = findNewRelationships(relationshipsB, relationshipsC);

n_notInMetaNetXC = length(find(inMetaNetXC==0));
exportNewRelationships_general(relationshipsC, relationships_equationsC, ...
    relationships_languageC, inMetaNetXC, n_notInMetaNetXC, relationships_MNXIDsC, ...
    relationships_modelIndicesC, ind2, 'newRel_global2', 'lpl_bpe')

disp('')

end